# Generated by Django 6.1.1 on 2026-09-26 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeerManagementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='management_units', to='regulations.huntingzone')),
            ],
        ),
        migrations.AddField(
            model_name='huntingseason',
            name='dmu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hunting_seasons', to='regulations.deermanagementunit'),
        ),
    ]
