# Generated by Django 6.1.1 on 2026-09-26 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0002_deermanagementunit_huntingseason_dmu'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'harvest categories',
            },
        ),
        migrations.AddField(
            model_name='huntingseason',
            name='harvest_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hunting_seasons', to='regulations.harvestcategory'),
        ),
    ]
