# Generated by Django 6.1.1 on 2026-09-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0003_harvestcategory_huntingseason_harvest_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasontype',
            name='code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
