# Generated by Django 6.1.1 on 2026-09-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0004_seasontype_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasontype',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
