# Generated by Django 6.1.1 on 2026-10-03 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0005_alter_seasontype_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BagLimitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.CharField(max_length=9)),
                ('limit_type', models.CharField(choices=[('DAILY', 'Daily'), ('POSSESSION', 'Possession'), ('SEASON', 'Season'), ('ANNUAL', 'Annual')], max_length=20)),
                ('limit', models.PositiveIntegerField(blank=True, null=True)),
                ('is_unlimited', models.BooleanField(default=False)),
                ('conditions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dmu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bag_limit_rules', to='regulations.deermanagementunit')),
                ('harvest_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bag_limit_rules', to='regulations.harvestcategory')),
                ('land_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bag_limit_rules', to='regulations.landtype')),
                ('season_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bag_limit_rules', to='regulations.seasontype')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bag_limit_rules', to='regulations.source')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bag_limit_rules', to='regulations.species')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bag_limit_rules', to='regulations.huntingzone')),
            ],
        ),
    ]
