# Generated by Django 6.1.1 on 2026-10-03 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0006_baglimitrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.CharField(blank=True, max_length=9)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('land_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regulation_notes', to='regulations.landtype')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regulation_notes', to='regulations.source')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulation_notes', to='regulations.species')),
            ],
        ),
    ]
