# Generated by Django 6.1.1 on 2026-10-04 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0007_regulationnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatoryArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('map_url', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='baglimitrule',
            name='season_group',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='baglimitrule',
            name='regulatory_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bag_limit_rules', to='regulations.regulatoryarea'),
        ),
        migrations.AddField(
            model_name='huntingseason',
            name='regulatory_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hunting_seasons', to='regulations.regulatoryarea'),
        ),
    ]
