# Generated by Django 6.1.1 on 2026-10-06 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0008_regulatoryarea_baglimitrule_season_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('area_type', models.CharField(choices=[('WMA', 'Wildlife Management Area'), ('WEA', 'Wildlife and Environmental Area'), ('PSGHA', 'Public Small Game Hunting Area'), ('SGA', 'Small Game Area'), ('NWR', 'National Wildlife Refuge'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('acreage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True)),
                ('brochure_url', models.URLField(blank=True)),
                ('map_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='huntingseason',
            name='wma',
        ),
        migrations.AlterField(
            model_name='baglimitrule',
            name='limit_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('DAILY', 'Daily'), ('POSSESSION', 'Possession'), ('SEASON', 'Season'), ('ANNUAL', 'Annual')], max_length=20),
        ),
        migrations.AddField(
            model_name='baglimitrule',
            name='managed_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bag_limit_rules', to='regulations.managedarea'),
        ),
        migrations.AddField(
            model_name='huntingseason',
            name='managed_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hunting_seasons', to='regulations.managedarea'),
        ),
        migrations.DeleteModel(
            name='WildlifeManagementArea',
        ),
    ]
